#!/usr/bin/env python3
# Capture random bits

import sys
import os
import re

from pyutil import git_insert
from pyutil import get_datetime
from pyutil import decompose_markdown_link
from pyutil import url_remove_scheme
from pyutil import grep

template_header = '''\
# {month}

'''

template_entry = '''\
{link} {date_time}

---

'''


def new_clip(link):
    re_link = '\[.*\]\(.*\)'
    if re.search(re_link, link):
        print('Link')
        commit_message = 'clip'
        # echo back
        date_time = get_datetime()
        entry = template_entry.format(link=link, date_time=date_time)
        print(entry)
        # abort if already clipped
        title, url = decompose_markdown_link(link)
        url_without_scheme = url_remove_scheme(url)
        git_dir = os.path.dirname(os.environ['DOTFILES']) + '/clips'
        match = grep(url_without_scheme, git_dir + '/*.md')
        if match:
            print('Already clipped')
            print(match)
            return
        # insert entry
        month = get_datetime('%Y-%m')
        filename = os.path.join(git_dir, month) + '.md'
        header = template_header.format(month=month)
        at_line_no = 2
        git_insert(git_dir, filename, header, at_line_no, entry, commit_message)
    else:
        print('Undefined')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: clip '[title](url)'")
        sys.exit()

    new_clip(sys.argv[1])
