#!/usr/bin/env python3
# Append date and time to filename

import sys
import os
import os.path
import datetime

FORMAT = '%Y-%m-%d %H.%M.%S'

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: fdate FILE')
        sys.exit()

    file = sys.argv[1]
    if not os.path.exists(file):
        print(file, 'not exists.')
        sys.exit()

    date = datetime.datetime.now().strftime(FORMAT)

    split = file.split('.')
    if len(split) == 1:
        dest = file + ' ' + date
    elif len(split) > 1:
        split[-2] = split[-2] + ' ' + date
        dest = '.'.join(split)

    os.rename(file, dest)
