#!/usr/bin/env python3
# Get more done

import sys
import os
import re

from pyutil import git_update
from pyutil import git_commit
from pyutil import ensure_file
from pyutil import insert_into
from pyutil import get_datetime

template_header = '''\
# {month}

'''

template_entry = '''\
{outline} {date_time}
'''


def new_outline(outline):
    re_todo = '- \[ \] .*'
    re_done = '- \[x\] .*'
    re_info = '- .*'
    if outline.startswith('- '):
        if re.search(re_todo, outline):
            print('TODO')
            commit_message = 'todo'
        elif re.search(re_done, outline):
            print('DONE')
            commit_message = 'done'
        else:
            print('INFO')
            commit_message = 'info'
        # echo back
        date_time = get_datetime()
        entry = template_entry.format(outline=outline, date_time=date_time)
        print(entry)
        # update
        outline_dir = os.path.dirname(os.environ['DOTFILES']) + '/outlines'
        git_update(outline_dir)
        # new file for new month
        month = get_datetime('%Y-%m')
        filename = os.path.join(outline_dir, month) + '.md'
        header = template_header.format(month=month)
        ensure_file(filename, header)
        # insert entry
        insert_into(filename, 2, entry)
        # commit
        git_commit(outline_dir, [filename], commit_message)
    else:
        print('Undefined')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: outline '- [ ] TODO'")
        print("       outline '- [x] DONE'")
        print("       outline '- INFO'")
        sys.exit()

    new_outline(sys.argv[1])
