#!/usr/bin/env bash
# Compute or check SHA256 message digest

if [[ $# -ne 1 || ! -f "$1" ]]; then
    echo Usage: check FILE
    exit
fi

if [[ -f "$1.SHA256SUM" ]]; then
    shasum -a 256 -c "$1.SHA256SUM"
else
    shasum -a 256 "$1" > "$1.SHA256SUM"
fi
