#!/usr/bin/env bash
# Compute or check SHA256 message digest

if [[ $# -ne 1 || ! -f "$1" ]]; then
    echo Usage: check FILE
    exit
fi

if [[ -f "$1.SHA256SUM" ]]; then
    sha256sum -c "$1.SHA256SUM"
else
    sha256sum "$1" > "$1.SHA256SUM"
fi
