#!/usr/bin/env bash
# Capture random bits

if [[ $# -ne 1 ]]; then
  echo "Usage: clip '[title](url)'"
  exit
fi

DIR="$(dirname "${DOTFILES}")/clips"
MONTH="$(date +%Y-%m)"
FILENAME="$DIR/$MONTH.md"
DATE_TIME="$(date +%Y-%m-%d\ %H:%M:%S\ %z)"

GLOB_LINK="\[*\](*)"

if [[ ! -d "$DIR" ]]; then
  # exit if DIR not exits
  echo "$DIR not exists"
  exit
else
  # update git repo
  (cd "$DIR" && git pull)
fi

# new file for new month
if [[ ! -f "$FILENAME" ]]; then
  echo "# $MONTH" >> "$FILENAME"
fi

# new clip
if [[ "$1" = $GLOB_LINK ]]; then
  echo Link
  sed -i "3i$1 $DATE_TIME\n\n---\n\n" "$FILENAME"
  (cd "$DIR" && git add "$FILENAME" && git commit -m "clip" && git diff HEAD^ HEAD)
else
  echo Undefined
fi
