#!/usr/bin/env bash
# Get more done

if [[ $# -ne 1 ]]; then
  echo "Usage: outline '- [ ] TODO'"
  echo "       outline '- [x] DONE'"
  echo "       outline '- INFO'"
  exit
fi

DIR="$(dirname "${DOTFILES}")/outlines"
MONTH="$(date +%Y-%m)"
FILENAME="$DIR/$MONTH.md"
DATE_TIME="$(date +%Y-%m-%d\ %H:%M:%S\ %z)"

GLOB_TODO="- \[ \] *"
GLOB_DONE="- \[x\] *"
GLOB_INFO="- *"

if [[ ! -d "$DIR" ]]; then
  # exit if DIR not exits
  echo "$DIR not exists"
  exit
else
  # update git repo
  (cd "$DIR" && git pull)
fi

# new file for new month
if [[ ! -f "$FILENAME" ]]; then
  echo "# $MONTH" >> "$FILENAME"
fi

# new TODO, DONE, INFO
if [[ "$1" = $GLOB_TODO ]]; then
  echo TODO
  sed -i "3i$1 $DATE_TIME" "$FILENAME"
  (cd "$DIR" && git add "$FILENAME" && git commit -m "todo" && git diff HEAD^ HEAD)
elif [[ "$1" = $GLOB_DONE ]]; then
  echo DONE
  sed -i "3i$1 $DATE_TIME" "$FILENAME"
  (cd "$DIR" && git add "$FILENAME" && git commit -m "done" && git diff HEAD^ HEAD)
elif [[ "$1" = $GLOB_INFO ]]; then
  echo INFO
  sed -i "3i$1 $DATE_TIME" "$FILENAME"
  (cd "$DIR" && git add "$FILENAME" && git commit -m "info" && git diff HEAD^ HEAD)
else
  echo Undefined
fi
